### PR TITLE
Add the ability to generate TOTP secrets against user accounts

### PR DESCRIPTION
**Pull request by SludgeGirl**
Hey!

So this looks to make the process of generating TOTP secrets for users easier, it doesn't handle any of the pam configuration for modules like pam_oath, but it's aim is to just help with the secrets themself

Bildschirmfoto_2024-10-11_13-15-23

### CODE REVIEW

**Comment by schubi2** [comment]
Hm, somehow it breaks the user settings save. Just  click "Save" in the "Save Settings to" section with TOTP enabled: 


ncaught TypeError: Cannot read properties of undefined (reading 'files')
    at AddUsersForm.vue:287:26
    at Array.forEach (<anonymous>)
    at Object.encodeToExport (AddUsersForm.vue:251:10)
    at EditView.vue:170:37
    at Array.forEach (<anonymous>)
    at Proxy.exportSettings (EditView.vue:170:6)
    at _createElementVNode.onClick._cache.<computed>._cache.<computed> (EditView.vue:446:15)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6706:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:6715:21)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:350:13)
﻿
I really like the layout !!!!

**Comment by schubi2** [comment]
P.S. : Sorry for being so late.....

**Comment by SludgeGirl** [comment]
> Hm, somehow it breaks the user settings save. Just click "Save" in the "Save Settings to" section with TOTP enabled:

Oh interesting! I'll take a look into that and add a test to cover it too

> P.S. : Sorry for being so late.....

No worries!

**Comment by SludgeGirl** [comment]
Alright, that should fix the error you were getting!

I also stumbled into another one when importing a user without a password, so I've included a patch for that and included a test case in the fixture for it

Let me know if there's anything else!

**Comment by schubi2** [comment]
> Let me know if there's anything else!
Thanks, looks really good now.

I must admit that I have had problems to understand how and by whom the generated file will be used for. 
The text:
"This will write a secret to /root/.pam_oath_usersfile this will not be used by default and needs extra steps" does not really helped here ;-)
I have also asked Fabian and Robert. Robert has said, that there will be additional docu available soon and he will make a new PR to point on it. Fabian has told me that the file will be currently used by Cockpit. Perhaps we should mention it too.
I would also say "Time-based one-time password (TOTP)" at one point. So the user has not have to google for TOTP.
I must admit....I have done :-)
So, perhaps we are finding some words for the user who is not so firm in TOTP in order to give him a hint if he add this feature.
fuel-ignition should be for users who have no deep knowledge about the system, but has to get a running machine in short time to fulfill the required tasks.

**Comment by SludgeGirl** [comment]
>  fuel-ignition should be for users who have no deep knowledge about the system, but has to get a running machine in short time to fulfill the required tasks.

Ah gotcha, yeah I fell quite short of that. That fixup should make the wording alot more user friendly, I've opted for the wording you suggested along with also including mention to an app based authentication since a few bigger services tend to reference the feature by that

Wording is admittedly not my strongest suit, so do let me know if you have any other suggestions

**Comment by schubi2** [comment]
> Wording is admittedly not my strongest suit
Me too :-)
I have asked Fabian about input and
I will merge it and will do little changes.

**Pull request merged**
